live_config_reload = true
window.opacity = 1

[colors.bright]
black = "0xbdae93"
blue = "0x076678"
cyan = "0x427b58"
green = "0x79740e"
magenta = "0x8f3f71"
red = "0x9d0006"
white = "0x282828"
yellow = "0xb57614"

[colors.cursor]
cursor = "0x504945"

[colors.normal]
black = "0xf9f5d7"
blue = "0x076678"
cyan = "0x427b58"
green = "0x79740e"
magenta = "0x8f3f71"
red = "0x9d0006"
white = "0x504945"
yellow = "0xb57614"

[colors.primary]
background = "0xf9f5d7"
foreground = "0x504945"

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Retina"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Medium"

[shell]
program = "zsh"

[window.padding]
x = 3
y = 3
